# Welcome to Serverless!
#
# This file is the main config file for your service.
#
# For full config options, check the docs:
#    docs.serverless.com
#

service: cicero-google-voice-action

provider:
  name: aws
  runtime: nodejs6.10
  apiKeys:
    - ciceroGoogleVoice
  stage: prod
  region: us-east-1

package:
  include:
    - lambda/**
  exclude:
    - deployment/**
    - dialogflow/**
    - scripts/**
    - Vagrantfile
    - .*
    - .vagrant/**
    - lambda/constants.js.example

functions:
  ciceroGoogleVoice:
    handler: lambda/index.handler
    events:
      - http:
           method: post
           path: ciceroGoogleVoice
           private: true

plugins:
  - serverless-offline
