---
- hosts: all
  become: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - { role: "azavea.aws-cli" }
    - { role: "azavea.unzip" }
    - { role: "azavea.ntp" }
    - { role: "azavea.python-security" }
    - { role: "azavea.docker" }
    - { role: "azavea.nodejs" }
    - { role: "cicero.app" }
